# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Home of Robert Morin
email: romorin@zoho.com
github: https://github.com/romorin
codepen: http://codepen.io/romorin/
freeCodeCamp: http://www.freecodecamp.com/romorin
description: >
  Robert Morin, programmer. See my works and skills, and learn how to see me
  around the web.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username: romorin

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
  - jekyll-assets
  - bootstrap-sass
  - uglifier
exclude:
  - Gemfile
  - Gemfile.lock

# Collections
collections:
  projects:
    output: true
  ? techs_cat
  ? techs
  ? credits


assets:
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - assets/javascripts
    - assets/stylesheets
